<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="View.aspx.cs" Inherits="Project.View" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Dashboard</title>
    <link rel="stylesheet" type="text/css" href="style.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
    <style>
    .row-spacing td {
        padding: 30px; /* Adjust the padding as needed */
    }
</style>
</head>
<body>
    <form runat="server">
        <div class="sidebar">
            <div class="logo_details">
                <i class="bx bxl-audible icon"></i>
                <div class="logo_name">Menu</div>
                <i class="bx bx-menu" id="btn"></i>
            </div>
            <ul class="nav-list">
                <li>
                    <a href="Admin.aspx">
                        <i class="bx bx-book"></i>
                        <span class="link_name">Dashboard</span>
                    </a>
                    <span class="tooltip">Dashboard</span>
                </li>
                <li>
                    <a href="View.aspx">
                        <i class="bx bx-book-reader"></i>
                        <span class="link_name">View</span>
                    </a>
                    <span class="tooltip">View</span>
                </li>
                 <li>
     <a href="Add.aspx">
         <i class="bx bx-book-add"></i>
         <span class="link_name">Add</span>
     </a>
     <span class="tooltip">Add</span>
 </li>
                <li>
                    <a href="Report.aspx">
                        <i class="bx bx-printer"></i>
                        <span class="link_name">Report</span>
                    </a>
                    <span class="tooltip">Report</span>
                </li>
                <li>
                <li class="profile">
                    <div class="profile_details">
                        <asp:Image ID="profileImage" runat="server" ImageUrl="pp.jpg" AlternateText="profile image" />
                        <div class="profile_content">
                            <div class="designation"><asp:Literal ID="lblUsername" runat="server" Text="Admin"/></div>
                        </div>
                    </div>
                    <i class="bx bx-log-out" id="log_out" runat="server" />
                </li>
            </ul>
        </div>
        <section class="home-section" style="margin-right:500px;">
            <div class="text">List of Book</div>
             <div>
                <asp:GridView ID="GridView1" runat="server" DataKeyNames="Id" AutoGenerateColumns="False" AutoGenerateDeleteButton="False"  CssClass="table table-bordered table-striped" OnSelectedIndexChanged="GridView1_SelectedIndexChanged1" OnRowCommand="GridView1_RowCommand" OnRowDeleting="GridView1_RowDeleting" OnRowUpdating="GridView1_RowUpdating" >
                <HeaderStyle BackColor="#6C757D" ForeColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Entry ID" SortExpression="EntryID" ItemStyle-CssClass="text-center" />
                    <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" ItemStyle-CssClass="text-center" />
                    <asp:BoundField DataField="Author" HeaderText="Author" SortExpression="Author" ItemStyle-CssClass="text-center" />
                    <asp:BoundField DataField="Genre" HeaderText="Genre" SortExpression="Genre" ItemStyle-CssClass="text-center" />
                    <asp:BoundField DataField="Year" HeaderText="Publication Year" SortExpression="Publication Year" ItemStyle-CssClass="text-center" />
                    <asp:BoundField DataField="ISBN" HeaderText="ISBN" SortExpression="ISBN" ItemStyle-CssClass="text-center" />
                    <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" ItemStyle-CssClass="text-center" />
                    <asp:TemplateField HeaderText="Actions">
                        <ItemTemplate>
                            <asp:LinkButton ID="lnkSelect" runat="server" CssClass="btn btn-primary btn-sm" Text="Update" CommandName="Update" CommandArgument='<%# Container.DataItemIndex %>' OnClientClick="return confirm('Are you sure you want to perform this action?');" />
                            <asp:LinkButton ID="lnkDelete" runat="server" Text="Delete" CommandName="Delete" CommandArgument='<%# Eval("Id") %>' OnClientClick="return confirm('Are you sure you want to delete this item?');" />
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <RowStyle CssClass="text-center" />
                <AlternatingRowStyle CssClass="text-center" />
                <HeaderStyle CssClass="text-center" />
                <RowStyle CssClass="row-spacing" />
                <AlternatingRowStyle CssClass="row-spacing" />
            </asp:GridView>
            </div>
        </section>
    </form>

    <script>
        document.getElementById("<%= log_out.ClientID %>").addEventListener("click", function () {
            window.location.href = "Default.aspx";
        });
    </script>
    <script src="script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-pzjw8f+ua/CJ7OBbbZXBwFt2TKXy5s4SPARx3S6oBlF7pPbzq4C+LBefzeD0tZwD" crossorigin="anonymous"></script>
</body>
</html>
